### ISSUE TITLE
Navigation/Cart

### ISSUE THREAD

**Issue by wllmlng** [1071919wl/heighten#3]
Hi Vanessa,

I think my Navigation/Cart functionality is ready for your review.
[Live Site](https://heighten-fullstack.herokuapp.com/#/)
My site was previously having navigation issues so I decided to wait until its fixed before sending this.

### Navigation
- [x] Anything that looks like it can be clicked on should have some functionality. (EXCEPT the search icon since its one of my other mvp).
- [x] You should be able to navigate through the pages using the drop down nav bar. Some of the links will lead to the same category page. At the moment, this is by design choice since i have yet to create a filter for each one (this will probably be with my search mvp if time permits). 

### Cart
- [x] User should be able to add and remove items from cart
- [x] Cart should keep track of quantity, product and estimate total
- [x] Update button and remove button should behave as expected
- [x] Products should remain in cart even when navigating away

**Comment by Vanchen07** [comment]
- great job!
